version: "3"
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
