// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Loads the DATABASE_URL from prisma/.env.local (a local-dev-only file, not
// the app's own .env.development/.env.production) so this never collides
// with or gets confused for the application's real environment config.
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: "prisma/.env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
